import {
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpFromLine,
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  Bell,
  CircleCheck,
  CircleDollarSign,
  Clapperboard,
  Coins,
  Copy,
  CreditCard,
  Crown,
  FileBarChart,
  Gift,
  HandCoins,
  Headphones,
  Globe,
  Landmark,
  LayoutDashboard,
  ListChecks,
  Mail,
  Phone,
  LockKeyhole,
  LogOut,
  PieChart,
  Play,
  QrCode,
  Share2,
  UserPlus,
  UserRound,
  Users,
  Wallet,
} from "lucide-react";

export const iconMap = {
  LayoutDashboard,
  CreditCard,
  PieChart,
  ListChecks,
  CircleDollarSign,
  Play,
  DollarSign: BadgeDollarSign,
  BadgeDollarSign,
  UserPlus,
  Users,
  Wallet,
  FileBarChart,
  Bell,
  Headphones,
  UserRound,
  LogOut,
  BadgeCheck,
  CircleCheck,
  Crown,
  Coins,
  HandCoins,
  Gift,
  LockKeyhole,
  ArrowDownToLine,
  ArrowUpFromLine,
  ArrowLeftRight,
  QrCode,
  Landmark,
  Globe,
  Mail,
  Phone,
  Clapperboard,
  Banknote,
  Copy,
  Share2,
};

export default function AppIcon({ name, size = 18, className, strokeWidth = 2.25 }) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
